name: Kubeflow Pipeline

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: docker login
      run: | # log into docker hub account
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  

    - name: Build the Preprocess image
      run: docker build ./boston_housing/preprocess_data --tag jilanikashif/boston_pipeline_preprocessing
    - name: Push the Preprocess image
      run: docker push jilanikashif/boston_pipeline_preprocessing
      
    - name: Build the Train image
      run: docker build ./boston_housing/train --tag jilanikashif/boston_pipeline_train
    - name: Push the Train image
      run: docker push jilanikashif/boston_pipeline_train
      
    - name: Build the Test image
      run: docker build ./boston_housing/test --tag jilanikashif/boston_pipeline_test
    - name: Push the Test image
      run: docker push jilanikashif/boston_pipeline_test
      
    - name: Build the Deploy image
      run: docker build ./boston_housing/deploy_model --tag jilanikashif/boston_pipeline_deploy_model
    - name: Push the Deploy image
      run: docker push jilanikashif/boston_pipeline_deploy_model
